import json
import random
from datetime import datetime, timedelta
from pathlib import Path

# Unternehmen
COMPANY_INFO = {
    "ADS": "Adidas AG", "ALV": "Allianz SE", "BAS": "BASF SE", "BAYN": "Bayer AG", "BEI": "Beiersdorf AG",
    "BMW": "BMW AG", "CBK": "Commerzbank AG", "CON": "Continental AG", "1COV": "Covestro AG",
    "DHER": "Delivery Hero SE", "DBK": "Deutsche Bank AG", "DB1": "Deutsche Börse AG",
    "DTE": "Deutsche Telekom AG", "ENR": "Siemens Energy AG", "EOAN": "E.ON SE",
    "FME": "Fresenius Medical Care AG & Co. KGaA", "FRE": "Fresenius SE & Co. KGaA",
    "HEN3": "Henkel AG & Co. KGaA", "IFX": "Infineon Technologies AG", "LIN": "Linde plc",
    "MBG": "Mercedes-Benz Group AG", "MRK": "Merck KGaA", "MTX": "MTU Aero Engines AG", "MUV2": "Munich Re",
    "PAH3": "Porsche Automobil Holding SE", "PUM": "PUMA SE", "QIA": "Qiagen N.V.", "RWE": "RWE AG",
    "SAP": "SAP SE", "SIE": "Siemens AG", "SHL": "Siemens Healthineers AG", "SY1": "Symrise AG",
    "TKA": "thyssenkrupp AG", "VNA": "Vonovia SE", "VOW3": "Volkswagen AG", "ZAL": "Zalando SE",
    "HNR1": "Hannover Rück SE", "BNR": "Brenntag SE", "DWNI": "Deutsche Wohnen SE", "HEI": "Heidelberg Materials AG"
}

# Textbausteine
TITLES = [
    "Company faces regulatory pressure in Asia",
    "Expansion plans delayed due to supply chain issues",
    "Strong Q2 results beat expectations",
    "Leadership shakeup triggers market concerns",
    "Positive consumer trends drive up sales",
    "Olaf Scholz involved with corruption scandal with this company",
    "Xi Jingping approved of this new company",
    "Company under investigation for greenwashing",
    "Major data leak affects millions of customers",
    "CEO announces sudden resignation amid probe",
    "DAX company partners with Tesla for EV innovation",
    "Cyberattack halts operations temporarily",
    "Bafin launches probe into insider trading",
    "New partnership aims to boost ESG score",
    "Activist investors demand leadership change",
    "Global recall puts product safety in spotlight",
    "Positive forecast despite macro uncertainty",
    "Board approves controversial bonus plan",
    "Company joins Net Zero initiative",
    "Legal dispute with EU competition regulators escalates",
    "New factory in Eastern Europe raises ethical concerns",
    "Employee strikes disrupt logistics hub",
    "Breakthrough in hydrogen tech announced",
    "Audit reveals financial irregularities",
    "Major investor reduces stake",
    "Labor rights violations reported by NGO",
    "UN praises company’s sustainability efforts",
    "Executive bonuses draw public backlash",
    "Company enters African market for first time",
    "Green bond issuance oversubscribed",
    "Anonymous whistleblower reveals internal conflicts",
    "Surge in orders after viral TikTok campaign",
    "Ad campaign banned due to misinformation",
    "CEO linked to Panama Papers revelations",
    "ESG rating upgraded by Sustainalytics",
    "Layoffs announced amid restructuring",
    "Merger talks spark antitrust concerns",
    "NGO accuses company of rainforest destruction",
    "Former executive charged with embezzlement",
    "Robust dividend forecast pleases shareholders",
    "CFO departure spooks investors",
    "New law in US threatens business model",
    "Social media outrage forces policy reversal",
    "Rare earth supply deal strengthens tech vertical",
    "Customer satisfaction reaches all-time high",
    "Financial Times highlights innovation push",
    "Media outlets question political donations",
    "Controversial AI tool rolled out",
    "Carbon offset claims face skepticism",
    "Strong euro hurts export margins",
    "PR campaign fails to change narrative",
    "Greenpeace stages protest at HQ",
    "Company joins anti-corruption alliance",
    "Leaked emails suggest cover-up attempt",
    "Sustainable packaging initiative launched",
    "NGO ranks company best in labor standards",
    "Startup acquisition boosts R&D capabilities",
    "Bribery investigation widens in Southeast Asia",
    "NGO files complaint at European Court of Justice",
    "CEO earns spot on Time 100 list",
    "Lawsuit filed over toxic waste disposal",
    "Global expansion plan gets shareholder nod",
    "Corruption charges dropped after settlement",
    "Company ranked top employer in Europe",
    "Technical glitch delays product rollout",
    "Share buyback announced amid strong cash flow",
    "Factory explosion injures several workers",
    "Diversity program wins industry award",
    "Carbon-neutral milestone reached",
    "China market underperforms expectations",
    "Cybersecurity division gains strategic funding",
    "Journalist arrested after reporting on company",
    "ESG audit reveals major compliance gaps",
    "Patent infringement trial begins",
    "Q1 earnings miss analyst expectations",
    "Unions demand safer working conditions",
    "Media praises gender diversity initiatives",
    "Investigation launched into lobbying activities",
    "Inflation threatens profit margins",
    "Court rules against company in antitrust case",
    "IPO plans postponed due to market volatility",
    "Founder's biography sparks controversy",
    "Supply deal with Apple confirmed",
    "Internal report exposes toxic workplace culture",
    "Company wins EU innovation grant",
    "Scandal overshadows product launch",
    "Public trust erodes after false claims",
    "Company pushes for crypto adoption",
    "Hacktivists leak internal data",
    "NGO urges boycott over unethical sourcing",
    "GreenTech initiative faces execution delays",
    "Allegations of sexism in leadership emerge",
    "Stock soars after analyst upgrade",
    "German regulators demand increased transparency",
    "New ethical AI framework introduced",
    "Executive arrested in bribery scandal",
    "Company relocates HQ to Berlin",
    "Company fined €200M for price fixing",
    "Employee petitions for union recognition",
    "Crisis comms team overwhelmed by backlash",
    "Company adopts open-source strategy",
    "BASF involved in PFAS pollution debate",
    "BlackRock increases DAX exposure",
    "Volkswagen rebrands to distance from Dieselgate",
    "Bayer sued over herbicide-linked illnesses"
]

DESCRIPTIONS = [
    "Analysts react to the latest moves by the company amid market volatility.",
    "The outlook remains uncertain as management reevaluates global operations.",
    "Investors show optimism following the release of strong earnings.",
    "Shareholders express concern over the unexpected executive changes.",
    "Demand for key products continues to rise, fueling growth expectations.",
    "New findings of BaFin showed that Olaf Scholz might be involved with a corruption scandal with this specific company.",
    "In a shocking announcement, president Xi Jingping approved of a new technological advancement supporting environmental sustainability and potentially a higher ESG-Rating.",
    "Regulators in Asia allege violations in corporate practices related to environmental claims.",
    "Millions of customers affected after a massive breach of confidential records.",
    "The resignation raises questions about internal governance and oversight.",
    "The collaboration is expected to accelerate progress in electric vehicle production.",
    "All systems were shut down following the ransomware attack; investigations are ongoing.",
    "Authorities are probing transactions suspected to involve insider trading.",
    "The deal includes shared carbon neutrality goals and transparency commitments.",
    "Activist investors demand a complete board overhaul to increase accountability.",
    "Safety concerns rise as the company issues a global recall of popular products.",
    "Despite global uncertainty, the company maintains a stable outlook.",
    "Executive compensation criticized as excessive amid falling performance.",
    "This move aligns the company with global efforts to reduce emissions by 2030.",
    "Antitrust tensions heighten after EU formally files suit.",
    "NGOs raise alarms over potential labor exploitation in new regions.",
    "Delays in shipments due to strikes cause significant operational losses.",
    "Experts view this as a turning point for the company’s energy strategy.",
    "Auditors uncover inconsistencies in past financial disclosures.",
    "Market confidence drops after a major stakeholder sells off holdings.",
    "The NGO report alleges child labor in parts of the company’s supply chain.",
    "UN cites company’s proactive approach as a model for peers.",
    "Public opinion sours over performance-based bonuses during layoffs.",
    "The strategic move aims to capture untapped demand across Africa.",
    "Investors show strong interest in the company's new green financing.",
    "The whistleblower claims point to long-term internal dysfunction.",
    "A product feature gained popularity after viral social media exposure.",
    "Regulators flagged misleading claims in recent advertising materials.",
    "Public records connect the CEO to offshore accounts previously undisclosed.",
    "The upgrade reflects the company’s improved risk and governance framework.",
    "Job cuts are expected to affect up to 12% of the global workforce.",
    "Legal experts question whether the merger violates fair competition laws.",
    "New reports suggest company-linked operations in deforested areas.",
    "Prosecutors officially file charges against the former CFO.",
    "Dividend growth reflects robust fundamentals despite macro headwinds.",
    "Markets react negatively to the CFO's sudden exit.",
    "The law may challenge the company's revenue streams from digital services.",
    "The company reverses policy following online backlash and user protests.",
    "The rare earth agreement secures long-term access to key components.",
    "Survey results indicate a record high in customer satisfaction.",
    "The innovation drive receives international praise from trade magazines.",
    "Media investigations highlight unusually large political contributions.",
    "Privacy groups warn about ethical implications of the new AI rollout.",
    "Environmental groups scrutinize the legitimacy of carbon offset programs.",
    "Strong euro leads to declining competitiveness in export-heavy sectors.",
    "Rebranding efforts fall flat as public criticism mounts.",
    "Activists chain themselves to gates demanding transparency.",
    "Company becomes founding member of new industry integrity pact.",
    "Journalists obtain internal memos suggesting intent to conceal risks.",
    "The campaign targets plastic-free packaging in all product lines.",
    "Company hailed as industry leader in ethical labor practices.",
    "The acquisition adds new capabilities in biotech innovation.",
    "Allegations emerge of bribery in contract bids across ASEAN markets.",
    "The NGO brings the issue before international courts.",
    "Recognition follows CEO's role in driving corporate sustainability.",
    "Toxic dumping charges bring scrutiny to historical waste practices.",
    "The vote clears the way for major new global investments.",
    "Prosecutors dismiss charges after negotiated restitution.",
    "Company tops employee satisfaction rankings across multiple countries.",
    "Launch delay linked to software flaws discovered post-production.",
    "Buyback plan seeks to boost shareholder confidence.",
    "Explosion leads to renewed calls for factory safety inspections.",
    "Initiative wins top prize in workplace inclusion awards.",
    "Carbon footprint reductions verified by independent auditor.",
    "China remains a key but challenging growth market.",
    "Strategic funding to expand digital protection infrastructure.",
    "Authorities detain reporter investigating tax evasion schemes.",
    "Audit finds shortfalls in meeting sustainability promises.",
    "Court to decide over disputed technology patents.",
    "Weak sales in key regions contribute to revenue miss.",
    "Unions say workplace conditions fall short of legal standards.",
    "Media commends board for gender diversity efforts.",
    "Watchdogs question scope of government influence.",
    "Cost pressures from inflation could reduce net margins.",
    "Court finds company guilty of anticompetitive behavior.",
    "IPO plans now on hold pending improved macro conditions.",
    "Memoir draws attention to questionable past decisions.",
    "Apple confirms multi-year procurement agreement.",
    "Report reveals high stress and burnout across teams.",
    "Funding helps accelerate prototype development.",
    "Reputational damage from scandal delays growth plans.",
    "Public doubts credibility after misleading environmental claims.",
    "Company invests heavily in blockchain and crypto solutions.",
    "Leaked documents reveal surveillance of labor unions.",
    "NGO launches campaign to boycott products.",
    "Execution issues delay GreenTech project timeline.",
    "Board accused of turning a blind eye to harassment complaints.",
    "Stock rallies following bullish outlook revision.",
    "Authorities mandate stricter disclosures on lobbying.",
    "Ethical committee unveils machine learning code of conduct.",
    "Senior official arrested after internal audit leak.",
    "New HQ reflects growing digital and ESG focus.",
    "Fines relate to long-standing cartel operations in chemicals.",
    "Employees launch petition for collective bargaining rights.",
    "Crisis team struggles to manage narrative across platforms.",
    "Opens access to external developers via open-source release.",
    "Pollution findings linked to production site.",
    "Major fund increases exposure to German blue-chips.",
    "Branding refresh aimed at rebuilding consumer trust.",
    "Legal risks mount over health impacts of legacy products."
]

SOURCES = ["Boomberg", "Reuter", "BNBC", "Handelszeitung", "Financial Mimes",
           "Harbard Guiness School", "Moseleck News", "TikTok Finance", "Instagram Reels"]

# Zielverzeichnis
output_dir = Path("dummy_news")
output_dir.mkdir(exist_ok=True)

# Zeitraum
start_date = datetime(2023, 1, 2)
end_date = datetime.today()
date_list = [start_date + timedelta(days=x) for x in range((end_date - start_date).days + 1)]

# Dummy-Daten-Generator
def generate_dummy_entry(ticker, company_name, date):
    score = round(random.uniform(-1, 1), 3)
    label = "positive" if score > 0.2 else "negative" if score < -0.2 else "neutral"
    return {
        "date": date.strftime("%Y-%m-%d"),
        "ticker": ticker,
        "company_name": company_name,
        "title": random.choice(TITLES),
        "description": random.choice(DESCRIPTIONS),
        "url": f"https://www.{random.choice(SOURCES).lower()}.com/article/{random.randint(1000,9999)}",
        "source": random.choice(SOURCES),
       
    }

# Erstellung der JSON-Dateien
for ticker, name in COMPANY_INFO.items():
    news_entries = [generate_dummy_entry(ticker, name, date) for date in date_list]
    file_path = output_dir / f"{ticker}_trusted.json"
    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(news_entries, f, ensure_ascii=False, indent=2)

print(f"✅ Für {len(COMPANY_INFO)} Unternehmen wurden Newsdaten von {start_date.date()} bis {end_date.date()} erstellt.")
